### PR TITLE
fix for first row being swallowed

### PR DESCRIPTION
**Pull request by benjamine**

### CODE REVIEW

**Comment by parthakkar** [comment]
Omg I love you!

**Comment by benjamine** [comment]
"There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors." :)

**Comment by stardotbmp** [comment]
with `i` being declared as `0` immediately above isn't a check for `i >= 0` redundant?

I have removed this comparison altogether. No ill side effects I have noticed yet.

**Comment by bradjasper** [comment]
This got merged in https://github.com/bradjasper/ImportJSON/pull/18

**Pull request closed without merging**
